// Auto-resizing textarea, obtained at https://stackoverflow.com/a/25621277 (and modified)
window.onload = function () {
    const tx = document.getElementsByTagName('textarea');
    for (let i = 0; i < tx.length; i++) {
        tx[i].setAttribute('style', 'height:' + (tx[i].scrollHeight) + 'px;overflow-y:hidden;');
        tx[i].addEventListener("input", OnInput, false);
    }
    window['currentGroups'] = [];
    window['previousGroups'] = {
        people: [],
        groups: []
    };
};

function OnInput() {
    hideError();
    this.style.height = 'auto';
    this.style.height = (this.scrollHeight) + 'px';
}
// End of auto-resizing textarea, obtained at https://stackoverflow.com/a/25621277 (and modified)


function adjustTextArea() {
    groupsForm.people.style.height = 'auto';
    groupsForm.people.style.height = (groupsForm.people.scrollHeight) + 'px';
}


// Random number in an interval, obtained at https://stackoverflow.com/a/7228322 (and modified)
function randomIntFromInterval(min, max) { // min and max included
    if (min >= max) {
        return min;
    }
    return Math.floor(Math.random() * (max - min + 1) + min);
}
// End of random number in an interval, obtained at https://stackoverflow.com/a/7228322 (and modified)


// Download file from text, obtained at https://stackoverflow.com/a/18197341 (and modified)
function download(text) {
    var element = document.createElement('a');
    element.setAttribute('href', 'data:text/json;charset=utf-8,' + encodeURIComponent(text));
    element.setAttribute('download', 'groups.json');

    element.style.display = 'none';
    document.body.appendChild(element);

    element.click();

    document.body.removeChild(element);
}
// End of download file from text, obtained at https://stackoverflow.com/a/18197341 (and modified)


function hideError() {
    document.getElementById('error').style.visibility = '';
}

function displayError(message) {
    document.getElementById('error').style.visibility = 'visible';
    document.getElementById('error').textContent = message;
    return false;
}

function loadPreviousGroups() {
    hideError();
    let file = groupsForm.previousGroups.files[0];
    if (file.type.toLowerCase().indexOf('json') < 0) {
        groupsForm.previousGroups.value = '';
        return displayError('Please choose a .json file previously generated by this page.');
    }

    const reader = new FileReader();
    reader.addEventListener('load', (event) => {
        window['previousGroups'] = JSON.parse(decodeURIComponent(atob(event.target.result.replace('data:application/json;base64,', ''))));
        if (window['previousGroups'].people) {
            groupsForm.people.value = previousGroups.people.join("\n");
            adjustTextArea();
        } else {
            window['previousGroups'].people = [];
        }
        if (!window['previousGroups'].groups) {
            window['previousGroups'].groups = [];
        }
    });
    reader.readAsDataURL(file);
}

function pickGroups(max, min = 0) {
    window['currentGroups'] = [];
    // Splitting the lines, trimming them, removing non-letters from the beginning of each one and removing the empty ones
    let people = groupsForm.people.value.split("\n").map(function (word) {
        return word.trim().replace(/^[\d]*[\W]*/, '').trim();
    }).filter(function (word) {
        return word.length > 0;
    });

    // Removing all duplicate lines
    people = [...new Set(people)];
    window['previousGroups'].people = [...people];
    groupsForm.people.value = window['previousGroups'].people.join("\n");
    adjustTextArea();

    if (people.length <= 1) {
        return displayError('Please enter at least two different people below.');
    }

    let groups = [];
    while (people.length) {
        let group = [];

        for (let i = 0; i < max && people.length; ++i) {
            let person = randomIntFromInterval(0, people.length - 1);
            group.push(people.splice(person, 1)[0]);
        }

        groups.push(group);
    }

    window['currentGroups'] = groups;

    groups = groups.map(function (group) {
        return group.join(', ');
    });

    document.getElementsByTagName('ol')[0].innerHTML = '<li>' + groups.join('</li><li>') + '</li>'
    document.getElementsByTagName('main')[0].style.display = 'block';
}

function downloadGroups() {
    let previous = [...window['previousGroups'].groups];
    window['previousGroups'].groups.push(window['currentGroups']);
    download(encodeURIComponent(JSON.stringify(window['previousGroups'])));
    window['previousGroups'].groups = previous;
}

function resetGroups() {
    window['currentGroups'] = [];
    window['previousGroups'] = {
        people: [],
        groups: []
    };
    groupsForm.reset();

    adjustTextArea();
    document.getElementsByTagName('ol')[0].innerHTML = '';
    document.getElementsByTagName('main')[0].style.display = '';
}